#!/bin/sh -eu

. $(dirname $0)/../core/runner

testname="minimal-input"

banner "${testname}"
#----------

OUTPUT_DIR=${TEST}

mkdir -p ${OUTPUT_DIR}

INPUT_FILE=${OUTPUT_DIR}/empty
OUTPUT_FILE=${OUTPUT_DIR}/output

# Create a minimal file
echo '{}' > ${INPUT_FILE}

retcode=0
${HJSMIN} --input ${INPUT_FILE} --output ${OUTPUT_FILE} || retcode=1

if test ${retcode} -eq 0 ; then
  pass_test
else
  fail_test
fi
